spring.application.name=Musicboxd

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.qnsgvscepyluxdgpgczu
spring.datasource.password=lagoadocarro
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=3
# Application Configuration
spring.jmx.enabled=false
server.port=8080